# Generated by Django 2.2.12 on 2021-02-24 09:23

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('number', models.IntegerField(default=books.models.num, verbose_name='编号')),
            ],
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserToSc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.ManyToManyField(through='books.UserToSc', to='books.Novel', verbose_name='num1'),
        ),
        migrations.CreateModel(
            name='NumToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Novel')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.NovelTag')),
            ],
        ),
        migrations.AddField(
            model_name='noveltag',
            name='number',
            field=models.ManyToManyField(through='books.NumToTag', to='books.Novel', verbose_name='num'),
        ),
        migrations.CreateModel(
            name='NovelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('introduce', models.CharField(max_length=999, verbose_name='介绍')),
                ('up', models.IntegerField(default=books.models.up_num, verbose_name='点赞')),
                ('serialize', models.BooleanField(default=1, verbose_name='连载状态')),
                ('vip_type', models.BooleanField(default=0, verbose_name='VIP可阅读')),
                ('cover', models.ImageField(null=True, upload_to='cover', verbose_name='封面')),
                ('novel_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Novel', verbose_name='小说编号')),
            ],
            options={
                'ordering': ['-up'],
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='mail',
            field=models.ManyToManyField(through='books.UserToSc', to='books.User'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tag',
            field=models.ManyToManyField(through='books.NumToTag', to='books.NovelTag'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100, verbose_name='小说章节')),
                ('content', models.TextField(verbose_name='单章内容')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Novel')),
            ],
        ),
    ]
